#!/usr/bin/python3.8
from time import sleep
import sys
from subprocess import *
import re
import signal

filename = "qlen.txt"
flag = True


def signal_handler(signal, fname):
    global interrupted
    interrupted = True


signal.signal(signal.SIGINT, signal_handler)
interrupted = False


def qlen_monitoring(iface_="s1-eth1", interval_sec_=0.1, fname_=filename):
    global flag
    global interrupted
    current_time = 0
    pat_queued = re.compile(r'backlog\s[^\s]+\s([\d]+)p')
    cmd = "tc -s qdisc show dev %s" % iface_
    ret = []
    file = open("monitoring/{}".format(fname_), 'w')
    while not interrupted:
        p = Popen(cmd, shell=True, stdout=PIPE)
        output = p.stdout.read().decode('utf-8')
        matches = pat_queued.findall(output)
        if matches and len(matches) > 1:
            ret.append(matches[1])
            t = "%f" % current_time
            current_time += interval_sec_
            file.write(t + ' ' + matches[1] + '\n')
        sleep(interval_sec_)
    file.close()


try:
    iface = sys.argv[1]
    interval = float(sys.argv[2])
    file = sys.argv[3]
    qlen_monitoring(iface, interval, file)
except IndexError:
    print("Error. Please type interface name, interval_sec, file name!")
except InterruptedError:
    pass
finally:
    print("Unexpected error")
